### ISSUE TITLE
走形了

### ISSUE THREAD

**Issue by inshyma** [qkxyjren/LikeView#8]
使用❤Drawable   在绘制时变形了

**Comment by qkxyjren** [comment]
是设置使用图片后变形了吗，是的话方便把图片发过来一下吗-------- 原始邮件 --------主题：[qkxyjren/LikeView] 走形了 (#8)发件人：inshyma 收件人：qkxyjren/LikeView 抄送：Subscribed 使用❤Drawable   在绘制时变形了

**Comment by qkxyjren** [comment]
> 使用❤Drawable 在绘制时变形了

建议使用宽高比1:1的图片
